# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
   # Project Namespace in openshift for dev environment
   namespace_dev: dev-env
   # Project Namespace in openshift for dev environment
   namespace_prod: prod-env
   # Application name that needs to be deployed
   application_name: myreactwebapp
   # The above image registry comes from default-route of openshift internal registry
   image_registry: default-route-openshift-image-registry.apps.cluster-5qzhx.5qzhx.sandbox1541.opentlc.com 


stages:
  - stage: CI
    displayName: CI Stage
    jobs:
      - job: build
        displayName: build
        steps:
            - task: oc-cmd@3
              displayName: Create Dev openshift Project
              inputs:
                connectionType: 'OpenShift Connection Service'
                openshiftService: 'Openshift Connection'
                cmd: 'oc new-project dev-env'
                ignoreFlag: true
            - task: oc-cmd@3
              displayName: Start the build 
              inputs:
                connectionType: 'OpenShift Connection Service'
                openshiftService: 'Openshift Connection'
                cmd: 'oc new-build $(Build.Repository.Uri) -n $(namespace_dev) -l app=$(application_name)'
                ignoreFlag: true
  - stage: CD
    displayName: CD Stage
    jobs:
      - job: deploy
        displayName: deploy
        steps:
           - task: oc-cmd@3
             displayName: Deploy to Dev environemnt
             inputs:
               connectionType: 'OpenShift Connection Service'
               openshiftService: 'Openshift Connection'
               cmd: 'oc new-app --image $(image_registry)/$(namespace_dev)/$(Build.Repository.Name):latest'
                
            


          
