# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GIT_SHA: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)

stages:
  - stage: CI
    displayName: CI Stage
    jobs:
      - job: build
        displayName: build
        steps:
        - task: Docker@2
          displayName: Login to Quay
          inputs:
            containerRegistry: 'quay-container-registry'
            command: 'login'
        - task: Docker@2
          inputs:
            containerRegistry: 'quay-container-registry'
            repository: 'anattama/my-web-react-app:$(GIT_SHA)'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'


  

