# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
   # Project Namespace in openshift for dev environment
   namespace_dev: dev-env
   # Project Namespace in openshift for dev environment
   namespace_prod: prod-env
   # Application name that needs to be deployed
   application_name: myreactwebapp
   # The above image registry comes from default-route of openshift internal registry
   image_registry: default-route-openshift-image-registry.apps.cluster-5qzhx.5qzhx.sandbox1541.opentlc.com 
     

stages:
  - stage: CI
    displayName: CI Stage
    jobs:
      - job: build
        displayName: build
        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'

        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'


          
