name: build react app with github actions
on:
  workflow_dispatch: 
  push: 
   branches: 
     - main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4  

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
           registry: quay.io
           username: ${{ secrets.QUAY_USERNAME }}
           password: ${{ secrets.QUAY_ROBOT_TOKEN }}    
      
      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.QUAY_USERNAME }}/my-web-react-app:${GIT_SHA}
          file: ./Dockerfile
  
  