name: build react app with github actions
on:
  workflow_dispatch: 
  push: 
   branches: 
     - main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
           username: ${{ secrets.QUAY_USERNAME }}
           password: ${{ secrets.QUAY_PASSWORD }}    
      
      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.QUAY_USERNAME }}/project:latest
          file: ./Dockerfile
  
  